### ISSUE TITLE
User Profiles

### ISSUE THREAD

**Issue by paddyhockey1** [paddyhockey1/Anaheim-Ducks-Fanblog#10]
As an admin I should be able to access profiles in admin site to allow for changes to user's profile

- Profile can contain items like: first name, last name, bio, and user's custom images.

- This allows users to make changers to their user profile in the administration site.

**Comment by KERERCVASD** [comment]
maybe this will help
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)
